### ISSUE TITLE
update creating new so multiple text/rect for state

### ISSUE THREAD

**Issue by timelyportfolio** [ramnathv/rcstatebin#3]
`update` appears to `enter`/`append` rather than `update`.  As an example, after changing the dropdown 3 times, I get 3 `text`/`rect` pairs for each state.

![image](https://cloud.githubusercontent.com/assets/837910/7219514/080e8f32-e66a-11e4-87ab-2981f07116ac.png)

**Comment by ramnathv** [comment]
Thanks @timelyportfolio . It should be fixed now.
